language: node_js
node_js:
  - "node"
  - "lts/*"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - lint
  - test
  - build
  - docs

jobs:
  include:
    - stage: lint
      script: "yarn lint"
    - stage: test
      node_js: node
      script: "jest test --coverage && cat ./coverage/lcov.info | coveralls && rm -Rf ./coverage"
    - stage: build
      script: "yarn build"
    - stage: docs
      script: "yarn docz build"
